---

- name: Apply common configuration to all target nodes
  hosts: all
  user: user
  sudo: yes
  roles: 
    - common


- name: Install all the packages and stuff required for a webserver
  hosts: webservers
  user: user
  sudo: yes
  roles:
    - nginx

- name: Install all the packages and stuff required for a Database Server
  hosts: dbservers
  user: user
  sudo: yes
  roles:
    - redis
